---
:concurrency: 1
:max_retries: 3

:timeout: 8

:queues:
  - default
  - low
  - critical
  - mailers
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
